### PR TITLE
password matching changes

### PR DESCRIPTION
**Pull request by SujayDas1999**
Evidence of unit test cases passing
image

Changes - 
Now password and confirm password are matched by using crypto library. At first we hash both the password and then match them using the library function timingSafeEqual

The crypto.timingSafeEqual() function is used to determine whether two variables are equal without exposing timing information that may allow an attacker to guess one of the values.

Added regex for password length comparison

### CODE REVIEW

**Comment by SujayDas1999** [comment]
However I argue that there is not need to modify the existing password matching logic since it happens in server side. Although if pressed, we can go with the above approach.

**Comment by Colin-Stark** [comment]
I like what you are doing and appreciate it but lets go with just bcrypt. If you want i can include you in future issues

**Comment by SujayDas1999** [comment]
Unfortunately Bcrypt does not have a functionality to compare two strings, we need to hash one string and hash to compare both of them.

**Comment by SujayDas1999** [comment]
Modified the file with bcrypt to check password, but I still feel checking password and confirm password by converting it into hash using bcrypt is unnecessary. A simple plain === should just work fine.

**Comment by Colin-Stark** [comment]
> Modified the file with bcrypt to check password, but I still feel checking password and confirm password by converting it into hash using bcrypt is unnecessary. A simple plain === should just work fine.

We are saying the same thing, if you look at the one i did, an error is thrown when !== 

The only thing required is to use regex for the length test and not if statements. Plus your if statements are irregular, one has {} while the other just write the statement since it is one line. 

Multiple function call, I am trying to prevent that if it can be done in one

The password is hashed because it will be saved in the database

**Pull request merged**
